name: rspec

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'bin/*'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'bin/*'

jobs:
  rspec:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Run tests
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
        run: |
          cp config/database.example.yml config/database.yml
          cp config/application.example.yml config/application.yml
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake db:test:prepare
          bundle exec rake populate:users # not needed for tests but checking that it works is useful
          bundle exec rake spec

